language: node_js
node_js:
  - "8"

services:
  - docker

install:
- docker build -t uiveri5-base:latest .
 
#before_script:
#  - npm install

script:
  - ls -l
  - pwd
  - docker run --name myslave -e user=$user -e password=$password -v $PWD:/test/ -v /var/run/docker.sock:/var/run/docker.sock -dit uiveri5-base:latest /bin/bash
  - docker ps
  - sleep 10
  - docker ps
  - docker exec -d myslave /opt/selenium/startSeleniumServer.sh
  - sleep 10
  - docker exec -ti myslave bash -c "apt-get update && exit"
  - docker exec myslave bash -c "cd /test/test && ./test1.sh"
  - docker exec myslave bash -c "cd /test/test && ./test2.sh"
