language: node_js
node_js:
  - "8"

services:
  - docker

install:
- docker build -t uiveri5-base:latest .
 
#before_script:
#  - npm install

script:
  - ls -l
  - pwd
  - docker run --name myslave -e user=$user -e password=$password -v $PWD:/test/ -dit uiveri5-base:latest /bin/bash
  - docker ps
  - sleep 10
  - docker ps
  - docker exec -d myslave /opt/selenium/startSeleniumServer.sh
  - sleep 10
  - docker exec -d myslave bash -c "cd /test/test && ./test1.sh"
  - sleep 60
  - ls test/shared/results/reports
  - rm -f -R test/shared/results/reports
  - ls test/shared/results/
  - echo "check files"
  - docker exec -d myslave bash -c "cd /test/test && ./test2.sh"
  - sleep 60
  - ls test/shared/results/reports
  - echo "check files"
